name: CI

on:
  push:
    branches: [master]

jobs:
  actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: run build process
        run: npm run build --if-present
      - name: run tests
        run: npm test
      - name: Check test Coverage
        run: npm run test:coverage
